import type { Metadata } from "next"
import "./globals.css"
import Header from "@/components/Header"
import SkipToContent from "@/components/SkipToContent"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SkipToContent />
        <Header />
        <main
          id="main-content"
          className="flex-1 mt-[var(--thd-nav-h-sm)] sm:mt-[var(--thd-nav-h-lg)]"
        >
          {children}
        </main>
        <footer>FOoter</footer>
      </body>
    </html>
  )
}
